### ISSUE TITLE
Make the update script explain what it does

### ISSUE THREAD

**Issue by wbazant** [gxa/anatomogram#1]
Currently the script runs and doesn't tell the user "well done" or what it did, which makes it a bit confusing. Also the .py extension makes you wonder how you run it, .sh would be clearer.

You could consider switching to very simple makefiles, they would be easier to follow documentation for!

make save-svg-change
make show-demo-page

**Comment by alfonsomunozpomer** [comment]
You can also define tasks for `npm` in `package.json`.

**Comment by wbazant** [comment]
Done.
