### ISSUE TITLE
Snap vs react-svg

### ISSUE THREAD

**Issue by alfonsomunozpomer** [gxa/anatomogram#3]
In reply to https://github.com/adobe-webplatform/Snap.svg/issues/341#issuecomment-323074475:
> @alfonsomunozpomer, I saw that you're using react-svg in https://github.com/gxa/anatomogram, but I didn't see Snap.svg. Are you still using it?
> 
> I know it was an old post, but I'm trying to figure out how to integrate complex SVG manipulation (partly generated by mermaid.js) into an app based on create-react-app (which uses Webpack but doesn't expose its configuration options.)
> 
> I could just have a flow like:
> 
>   1. Generate SVG in mermaid.js
>   2. Parse and manipulate it in Snap.svg
>   3. Put it in my react component using react-svg.
> 
> But that seems bad because my SVGs are likely to get big and I'm going to want to be able to treat small parts of them like components themselves. I'm pondering a workflow (if I can figure out how to do it) more like:
> 
>   1. Generate SVG in mermaid.js
>   2. Parse it in Snap.svg
>   3. Send that to a react component hierarchy where different components render (and handle ui interactions with) different Snap elements.
>   4. Try to keep updates limited to Snap and the react components and not regenerate from mermaid.js except for the biggest changes (like all new data or something).
> 
> Does that seem like an ok approach? There are a lot of parts of it I don't know how to make work yet.

@Sigfried No, we currently moved away from Snap because to bundle it as a dependency you need `imports-loader` or `file-loader`, and ultimately Webpack. Therefore if users of your package use Browserify or other tool other than Webpack to bundle their code, they’re out of luck.

In our case we manipulate certain parts of the SVG using the DOM API. Our case is rather simple and it’s enough for what we need, but I understand that for complex manipulations (scaling, translating, animations, etc.) Snap can make your job a lot easier. What I don’t understand is why you need `react-svg` at all. Why can’t you do all the manipulations using Snap?

**Comment by Sigfried** [comment]
Oh, just because I saw you guys were using it, so I thought that might be part of the solution. I'm using @geelen's https://github.com/geelen/Snap.svg-cjs, which totally solved the webpack thing for me. As for the rest, it's looking easier than I thought. I'll post what I'm doing in a bit. Thanks!

**Comment by gxa** [comment]
Thanks for sharing! I had a look at your code. It’s a useful starting point if we ever need some more complex interactions.
